package org.chromium.components.crx_file;

public enum VerifierResult {
    OK_FULL,
    OK_DELTA,
    ERROR_FILE_NOT_READABLE,
    ERROR_HEADER_INVALID,
    ERROR_EXPECTED_HASH_INVALID,
    ERROR_FILE_HASH_FAILED,
    ERROR_SIGNATURE_INITIALIZATION_FAILED,
    ERROR_SIGNATURE_VERIFICATION_FAILED,
    ERROR_REQUIRED_PROOF_MISSING
}
